### ISSUE TITLE
Add more information to README.md

### ISSUE THREAD

**Issue by socialized0** [jeffalo/BEsUP#13]
### Is this suggestion related to an issue?
NO.
### What do you want?
Add more info to README.md, like the ST, the policy topic, and more. I don't even care. Add stuff.

### *Kind regards,*
*AAAAAAAAAAAAAAAAAAAAAAAAA*

**Comment by jeffalo** [comment]
done in 234dccdf43d2e8a75df03cd055713a91b2dfb633
