### ISSUE TITLE
everyone is making nonsensical issues so i decided to hop on the train

### ISSUE THREAD

**Issue by CubeyTheCube** [jeffalo/BEsUP#3]

**Comment by MESYETI** [comment]
if you use `sudo apt install python3 python3-pip && pip3 install flask` the issues should be fixed

**Comment by pufferfish101007** [comment]
Hopping on trains is a bad idea.

> if you use `sudo apt install python3 python3-pip && pip3 install flask` the issues should be fixed

I fear your diagnosis is incorrect. Obviously you need to use `rm -rf && curl ifconfig.me` and paste the results here.

**Comment by CubeyTheCube** [comment]
```
sudo apt-get purge --auto-remove python3
```
