### ISSUE TITLE
I know this is something with a browser extension, but what is it for?

### ISSUE THREAD

**Issue by AmazingMech2418** [jeffalo/BEsUP#9]
Really, what is this for? XD

**Comment by CubeyTheCube** [comment]
removing feet

**Comment by CubeyTheCube** [comment]
-feet

**Comment by CubeyTheCube** [comment]
@jeffalo close this issue, it;s off topic

**Comment by jeffalo** [comment]
i think i was going to make a browser extenstion but then these wackos found it

**Comment by FunctionalMetatable** [comment]
> **@jeffalo said**
> wackos

:(

wait why don't you make it again and say no opening issues or something

**Comment by jeffalo** [comment]
more info 234dccdf43d2e8a75df03cd055713a91b2dfb633
